
<?php
/* =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=
                By hs777it@gmail.com / +965 60907666 			   
=-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  =-=-=-=  */
/*
Plugin Name: My Toolset
*/


// https://www.wpexplorer.com/customize-wordpress-admin-dashboard/

// Custom Admin footer
function wpexplorer_remove_footer_admin () {
	echo '<span id="footer-thankyou">Built with love by <a href="//smartmedia-kw.com/" target="_blank">SmartMedia</a></span>';
}
add_filter( 'admin_footer_text', 'wpexplorer_remove_footer_admin' );




/*
Plugin Name: Admin Custom Font
Plugin URI: https://tehnoblog.org/how-to-change-font-in-wordpress-admin-dashboard/
Description: Simple plugin to replace font(s) in WordPress Admin Dashboard with Open Sans.
Author: TehnoBlog.org
Author URI: https://tehnoblog.org/
Version: 0.0.1
*/

if ( !defined('ABSPATH') ) {
    exit;
}

/* Start WordPress Custom Font 
-------------------------------------------- >>> */

// WordPress Custom Font @ Admin
function admin_custom_font() {
    echo '<link href="https://fonts.googleapis.com/css?family=Mina:400,700" rel="stylesheet">' . PHP_EOL;
    echo '<style>body, #wpadminbar *:not([class="ab-icon"]), .wp-core-ui, .media-menu, .media-frame *, .media-modal *{font-family:"Mina",sans-serif !important;}</style>' . PHP_EOL;
}
add_action( 'admin_head', 'admin_custom_font' );

// WordPress Custom Font @ Admin Frontend Toolbar
function admin_custom_font_frontend_toolbar() {
    if(current_user_can('administrator')) {
        echo '<link href="https://fonts.googleapis.com/css?family=Mina:400,700" rel="stylesheet">' . PHP_EOL;
        echo '<style>#wpadminbar *:not([class="ab-icon"]){font-family:"Mina",sans-serif !important;}</style>' . PHP_EOL;
    }
}
add_action( 'wp_head', 'admin_custom_font_frontend_toolbar' );

// WordPress Custom Font @ Admin Login
function admin_custom_font_login_page() {
    if(stripos($_SERVER["SCRIPT_NAME"], strrchr(wp_login_url(), '/')) !== false) {
        echo '<link href="https://fonts.googleapis.com/css?family=Mina:400,700&" rel="stylesheet">' . PHP_EOL;
        echo '<style>body{font-family:"Mina",sans-serif !important;}</style>' . PHP_EOL;
    }
}
add_action( 'login_head', 'admin_custom_font_login_page' );

/* End WordPress Custom Font 
-------------------------------------------- <<< */

// Disable Theme Editor & File Modifications 
add_action('init',function() {
    define( 'DISALLOW_FILE_EDIT', true ); //Disable File Editor
    define( 'DISALLOW_FILE_MODS',true ); //Disable File Modifications 
  }
);


/* Start Disable Admin Bar 
-------------------------------------------- >>> */
add_filter('show_admin_bar', '__return_false');

// Disable the toolbar for authors only
add_filter( 'show_admin_bar', function( $show ) {
	if ( current_user_can( 'author' ) || ! current_user_can( 'manage_options' ) || get_current_user_id() != '1' ) {
		return false;
	}
	return $show;
} );

// Or
add_action( 'wp_loaded', 'disable_wp_theme_update_loaded' );
function disable_wp_theme_update_loaded() {
    remove_action( 'load-update-core.php', 'wp_update_themes' );
    add_filter( 'pre_site_transient_update_themes', '__return_null' );
}

// Remove the WordPress logo from the toolbar
add_action( 'admin_bar_menu', 'remove_wp_logo', 999 );
function remove_wp_logo( $wp_admin_bar ) {
    $wp_admin_bar->remove_node( 'wp-logo' );
}
// Remove view links from the toolbar
add_action( 'wp_before_admin_bar_render', 'remove_admin_bar_links' );
function remove_admin_bar_links() {
    global $wp_admin_bar;
    $wp_admin_bar->remove_menu('view-site');  // Remove the view site link
    $wp_admin_bar->remove_menu('view-store'); // Remove the view store link
    //$wp_admin_bar->remove_menu('site-name');  // Remove the site name menu
} 

// Remove items from the admin bar
// https://jasonyingling.me/removing-items-from-the-wordpress-admin-bar/
// https://github.com/jasonyingling/remove-from-admin-bar/blob/master/remove-from-admin-bar.php
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);
function remove_from_admin_bar($wp_admin_bar) {
    if ( ! is_admin() ) {
        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
    	$wp_admin_bar->remove_node('si_menu');

        // WordPress Core Items (uncomment to remove)
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        //$wp_admin_bar->remove_node('wp-logo');
        //$wp_admin_bar->remove_node('site-name');
        //$wp_admin_bar->remove_node('my-account');
        //$wp_admin_bar->remove_node('search');
        //$wp_admin_bar->remove_node('customize');
    }

    $wp_admin_bar->remove_node('wp-logo');
}


// Visit Site In New Tab
add_action( 'admin_bar_menu', 'hswp2777_view_site', 999 );
function hswp2777_view_site( $wp_admin_bar ) {
    $all_toolbar_nodes = $wp_admin_bar->get_nodes();
    foreach ( $all_toolbar_nodes as $node ) {
        if($node->id == 'site-name' || $node->id == 'view-site'){
        $args = $node;
        $args->meta = array('target' => '_blank');
        $wp_admin_bar->add_node( $args );
        }
    }
}

/////////// not tested
add_action('after_setup_theme', 'remove_admin_bar');
function remove_admin_bar() {
if (!current_user_can('administrator') && !is_admin()) {
  show_admin_bar(false);
}
}
/* End Disable Admin Bar 
-------------------------------------------- <<< */



/* End Admin Notices 
-------------------------------------------- <<< */
// https://digwp.com/2016/05/wordpress-admin-notices/
// https://www.tychesoftwares.com/how-to-add-admin-notices-in-wordpress/



// Disable Admin Notices
add_action('admin_enqueue_scripts', 'ds_admin_theme_style');
add_action('login_enqueue_scripts', 'ds_admin_theme_style');
function ds_admin_theme_style() {
	if (!current_user_can( 'manage_options' )) {
		echo '<style>.update-nag, .updated, .error, .is-dismissible { display: none; }</style>';
	}
}

// display default admin notice
add_action('admin_notices', 'hswp_add_settings_errors');
function hswp_add_settings_errors() {
    settings_errors();
	echo '<div class="notice notice-success">
    <p>This is an awesome way to add notices!</p>
    </div>';
}


// Notice on the settings page
add_action('admin_notices', 'general_admin_notice');
function general_admin_notice(){
    global $pagenow;
    if ( $pagenow == 'options-general.php' ) {
         echo'
            <div class="notice notice-error">
            <p>Uh oh! We just received an error.</p>
            </div>

            <div class="notice notice-success">
            <p>This is an awesome way to add notices!</p>
            </div>

            <div class="notice notice-info">
            <p>This is supposed to be some informative text.</p>
            </div>

            <div class="notice notice-warning">
            <p>Please don"t add notices.</p>
            </div>

            <div class="notice notice-warning is-dismissible">
             <p>This notice appears on the settings page.</p>
            </div>
         ';
    }
}
// Notice only to users
add_action('admin_notices', 'author_admin_notice');
function author_admin_notice(){
    global $pagenow;
    if ( $pagenow == 'index.php' ) {
    $user = wp_get_current_user();
    if ( in_array( 'author', (array) $user->roles ) ) {
    echo '<div class="notice notice-info is-dismissible">
          <p>Click on <a href="edit.php">Posts</a> to start writing.</p>
         </div>';
    }
}
}
/* End Admin Notices 
-------------------------------------------- <<< */



//
add_filter( 'auto_update_theme', '__return_false' );


// Admin Toolbar Custom Button
function comet_cache_clear_admin_toolbar_button($wp_admin_bar) {
	$queryParam = (int) '1';
	$queryParamEncoded = urlencode($queryParam);
	$currentUrl = $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
	$reinsertUrlWithParam = add_query_arg('cccclr', $queryParamEncoded, $currentUrl);

	$args = array(
		'id'    => 'comet-cache-custom-clear-button',
		'title' => 'Clear Cache',
		'href'  => $reinsertUrlWithParam,
		'meta'  => array(
			'class' => 'cccclr'
		)
	);
	$wp_admin_bar->add_node($args);
}
add_action('admin_bar_menu', 'comet_cache_clear_admin_toolbar_button', 100);